import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AI } from "./action";
import { Nav } from "@/components/Nav";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        <div>
          <Nav />

          <AI>{children}</AI>
        </div>
      </body>
    </html>
  );
}
